version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: saml_postgres
    environment:
      POSTGRES_DB: saml_sso
      POSTGRES_USER: saml_user
      POSTGRES_PASSWORD: saml_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../internal/database/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saml_user -d saml_sso"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: